### ISSUE TITLE
Wrong button appearance on Firefox version >70

### ISSUE THREAD

**Issue by sebhal92** [krejdster/wykop-powermenu#3]
Ej, @krejdd, czemu twój dodatek na nowym firefox jest taki ciemny?
#krejdowemenu #powermenu #wykopkrejdowy #menukrejdowe #wykop #dodatek #dodatki #pytanie #pytaniedoeksperta

![ciemno_mi_w_oczy](https://user-images.githubusercontent.com/58229006/69658135-ea879f80-107b-11ea-8ecf-ebc0ecee7fd8.jpg)

**Comment by krejdster** [comment]
Fixed by a workaround.

https://github.com/krejdster/wykop-powermenu/commit/eee9564829ac64527da169f00d1bcf626265750f
